#!/usr/bin/env bash

echo "------ HOOK START - BUILD -------"

# Deepen the history of the original shallow repository created by git clone
# with --depth=1 option (git describe needs the latest tags to work)
git pull --depth=50

# Build image with arguments
docker build \
  --build-arg VERSION="$(git describe --always --tags)" \
  --build-arg VCS_URL="$(git config --get remote.origin.url)" \
  --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
  --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
  -t "$IMAGE_NAME" .

echo "------ HOOK END - BUILD -------"
