#!/usr/bin/env bash

echo "------ HOOK START - BUILD -------"

set -x

# Get git tag
GIT_TAG="$(git describe --always --tags)"

gkit status
git describe --tags
git rev-parse HEAD
git symbolic-ref HEAD
git tag
git log --oneline --decorate=short

# Build image with arguments
docker build \
  --build-arg VERSION="$GIT_TAG" \
  --build-arg VCS_URL="$(git config --get remote.origin.url)" \
  --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
  --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
  -t "$IMAGE_NAME" .

# If tag matches semantic version
if [[ "$GIT_TAG" != v* ]]; then
  echo 'Version number does not match semantic version'
  exit
fi

# Break the version into components
semver="${GIT_TAG#v}"
semver="${semver%%-*}"
semver=( ${semver//./ } )

major="${semver[0]}"
minor="${semver[1]}"
patch="${semver[2]}"

# Tag image
docker tag "$IMAGE_NAME" "${DOCKER_REPO}:${major}.${minor}.${patch}"
docker tag "$IMAGE_NAME" "${DOCKER_REPO}:${major}.${minor}"
docker tag "$IMAGE_NAME" "${DOCKER_REPO}:${major}"

# Push images
docker push "${DOCKER_REPO}:${major}.${minor}.${patch}"
docker push "${DOCKER_REPO}:${major}.${minor}"
docker push "${DOCKER_REPO}:${major}"

echo "------ HOOK END - BUILD -------"
