#!/usr/bin/env bash

echo "------ HOOK START - POST_PUSH -------"

# shellcheck disable=1091
. 'shlib/hooks.sh'

post_push_hook

# Notify MicroBadger
echo 'Notify MicroBadger'
curl -X POST https://hooks.microbadger.com/images/vladgh/deluge/BvOV7ec7tt2N207sgMKqFrGzSxs=

echo "------ HOOK END - POST_PUSH -------"
