#!/usr/bin/env bash

echo "------ HOOK START - POST_BUILD -------"

curl -X POST https://hooks.microbadger.com/images/vladgh/deluge/BvOV7ec7tt2N207sgMKqFrGzSxs=

echo "------ HOOK END - POST_BUILD -------"
