#!/usr/bin/env bash

echo "------ HOOK START - POST_BUILD -------"

curl -X POST https://hooks.microbadger.com/images/vladgh/awscliruby/mbMppUV6he_zmIGik-MeJ22K8a0=

echo "------ HOOK END - POST_BUILD -------"
