#!/usr/bin/env bash

echo "------ HOOK START - POST_BUILD -------"

curl -X POST https://hooks.microbadger.com/images/vladgh/puppet/uj5nZE_tFQ3DyNFvERhnamfJbis=

echo "------ HOOK END - POST_BUILD -------"
