#!/usr/bin/env bash

echo '------ HOOK START - POST_PUSH -------'

echo 'Load libraries'
# shellcheck disable=1090
. "$(pwd -P)/../shlib/hooks.sh"

run_post_push_hook 'https://hooks.microbadger.com/images/vladgh/puppet/uj5nZE_tFQ3DyNFvERhnamfJbis='

echo '------ HOOK END - POST_PUSH -------'
