#!/usr/bin/env bash

echo '------ HOOK START - POST_PUSH -------'

set -euo pipefail

echo 'Load libraries'
# shellcheck disable=1090
. "$(pwd -P)/../shlib/hooks.sh"

export WEBHOOK='https://hooks.microbadger.com/images/vladgh/puppet/uj5nZE_tFQ3DyNFvERhnamfJbis='

run_post_push_hook

echo '------ HOOK END - POST_PUSH -------'
