#!/usr/bin/env bash

echo '------ HOOK START - POST_PUSH -------'

echo 'Load libraries'
# shellcheck disable=1090
. "$(pwd -P)/../shlib/hooks.sh"

run_post_push_hook 'https://hooks.microbadger.com/images/vladgh/puppetserverdb/8d7IFiC0YkD1xJinK5UtgkQ88V0='

echo '------ HOOK END - POST_PUSH -------'
