#!/usr/bin/env bash

echo "------ HOOK START - BUILD -------"

docker build \
  --build-arg VERSION="$(git describe --always --tags)" \
  --build-arg VCS_URL="$(git config --get remote.origin.url)" \
  --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
  --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
  -t "$IMAGE_NAME" .

echo "------ HOOK END - BUILD -------"
