#!/usr/bin/env bash

echo "------ HOOK START - POST_BUILD -------"

curl -X POST https://hooks.microbadger.com/images/vladgh/apache/1LIUNGTtioEcpHJoQZzwK3qQPhE=

echo "------ HOOK END - POST_BUILD -------"
