#!/usr/bin/env bash

echo "------ HOOK START - POST_BUILD -------"

curl -X POST https://hooks.microbadger.com/images/vladgh/gpg/Sg_CkaULmDjZ0K3u5W1mIqXlkOk=

echo "------ HOOK END - POST_BUILD -------"
