#!/usr/bin/env bash

echo '------ HOOK START - POST_PUSH -------'

echo 'Load libraries'
# shellcheck disable=1090
. "$(pwd -P)/../shlib/hooks.sh"

notify_webhook 'https://hooks.microbadger.com/images/vladgh/backup/ZjbRHMtrAhl9V2MWjWmOR0KWlGc='

echo '------ HOOK END - POST_PUSH -------'
