#!/usr/bin/env bash

echo '------ HOOK START - BUILD -------'

set -euo pipefail

echo 'Deepen repository history'
git pull --depth=50

echo 'Load libraries'
# shellcheck disable=1090
. "$(pwd -P)/../shlib/hooks.sh"

run_build_hook

echo '------ HOOK END - BUILD -------'
