#!/usr/bin/env bash

echo '------ HOOK START - BUILD -------'

echo 'Load libraries'
# shellcheck disable=1090
. "$(pwd -P)/../shlib/hooks.sh"

docker_build_image

echo '------ HOOK END - BUILD -------'
