#!/usr/bin/env bash

echo '------ HOOK START - POST_PUSH -------'

echo 'Load libraries'
# shellcheck disable=1090
. "$(pwd -P)/../shlib/hooks.sh"

run_post_push_hook 'https://hooks.microbadger.com/images/vladgh/awscli/mbMppUV6he_zmIGik-MeJ22K8a0='

echo '------ HOOK END - POST_PUSH -------'
