#!/usr/bin/env bash

echo "------ HOOK START - POST_BUILD -------"

curl -X POST https://hooks.microbadger.com/images/vladgh/fpm/OG17Glgq8CvSRFJjkK5vdC_pn_A=

echo "------ HOOK END - POST_BUILD -------"
