#!/usr/bin/env bash

echo '------ HOOK START - POST_PUSH -------'

set -euo pipefail

echo 'Load libraries'
# shellcheck disable=1090
. "$(pwd -P)/../shlib/hooks.sh"

export WEBHOOK='https://hooks.microbadger.com/images/vladgh/fpm/OG17Glgq8CvSRFJjkK5vdC_pn_A='

run_post_push_hook

echo '------ HOOK END - POST_PUSH -------'
