---
name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    name: Draft release
    runs-on: ubuntu-26.04
    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@72967cdc98ddd3160f1fc3dff619de365e137dd0 # v7.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
