---
name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    name: Draft release
    runs-on: ubuntu-24.04
    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@693d20e7c1ce1a81d3a41962f85914253b518449 # v7.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
